name: 陆沉
description: 分享技术和快乐
meta_description: "分享技术和快乐"

markdown: kramdown
redcarpet:
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: rouge
logo: true
paginate: 20
baseurl: /
domain_name: 'https://luchen11.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            '/rss.xml'
author:         'luchen'
